name: Deploy to Digital Ocean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via rsync
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

          # Deploy each site
          rsync -avz --delete collector/ $SERVER_USER@$SERVER_IP:/var/www/collector.example.com/
          rsync -avz --delete reporting/ $SERVER_USER@$SERVER_IP:/var/www/reporting.example.com/
          rsync -avz --delete www/ $SERVER_USER@$SERVER_IP:/var/www/www.example.com/